"""
Django settings for dmarc_viewer project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/
https://docs.djangoproject.com/en/1.8/ref/settings/

Modify this file using docs for the used django version
https://docs.djangoproject.com/en/1.11/topics/settings/
https://docs.djangoproject.com/en/1.11/ref/settings/

"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DMARC_VIEWER_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DMARC_VIEWER_DEBUG", False)

GEO_LITE2_CITY_DB = os.path.join(BASE_DIR, "GeoLite2-City.mmdb")

# Whitelist host/domain names to prevent HTTP Host header attacks
# https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-ALLOWED_HOSTS
# NOTE: Override the setting here if you want to whitelist multiple names,
# if you only have one, you can also use the environment variable
allowed_host = os.environ.get("DMARC_VIEWER_ALLOWED_HOSTS")
ALLOWED_HOSTS = [allowed_host] if allowed_host else []

DEBUG_TOOLBAR_PATCH_SETTINGS = False
INTERNAL_IPS = (u'::1', u'127.0.0.1')

# Application definition

INSTALLED_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'super_inlines',
    'bootstrap3',
    'djangoformsetjs',
    'website'
    # TODO: Add `django-debug-panel` and `django-debug-toolbar` to optional or
    # developer requirements and add to INSTALLED_APPS and to routes
    # (dmarc_viewer.urls) if available.
    #'debug_toolbar',
    #'debug_panel'
)

BOOTSTRAP3 = {
    'set_required' : False
}

# This dict is available in any templates via a custom context processor.
# See `website.context` for more info
TEMPLATE_SETTINGS = {
    "use_dist": True
}

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'website.middleware.ajax_bootstrap_message'
]

# TODO: Needs an upgrade?
# https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware
# MIDDLEWARE_CLASSES = (
    #'debug_panel.middleware.DebugPanelMiddleware',
# )

ROOT_URLCONF = 'dmarc_viewer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context.options'
            ],
        },
    },
]

WSGI_APPLICATION = 'dmarc_viewer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dmarc_viewer_db',
        'USER': 'dmarc_viewer_db',
        'PASSWORD': os.environ.get("DMARC_VIEWER_DB_KEY", ""),
        'HOST': os.environ.get("DMARC_VIEWER_DB_HOST", "127.0.0.1")
    }
}

CACHES = {
    # 'default': {
    #     'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
    #     'LOCATION': '127.0.0.1:11211',
    # }
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
    }
}



# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "/var/www/dmarc_viewer/static/"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        # 'file': {
        #     'level': 'DEBUG',
        #     'class': 'logging.FileHandler',
        #     'filename': os.path.join(BASE_DIR, 'log/dmarc_viewer.log')
        # }
    },
    'loggers': {
        # 'parser': {
        #     'handlers': ['file'],
        #     'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO')
        # },
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    }
}